### ISSUE TITLE
Some questions about the curvature in the code

### ISSUE THREAD

**Issue by GDUT-Kyle** [claydergc/css_loam_velodyne#1]
Hello, thank you for sharing your project, how are the first and second derivatives of the Gaussian function generated in your code? The Gaussian function in the paper is related to the 't' value corresponding to each point in the segment, why can it be calculated in advance? Thanks.

**Comment by claydergc** [comment]
Hello,

Theoretically it shouldn't be calculated in advance, however, when testing my code with the KITTI Dataset, the fact of generating the derivatives as a function of 't' was too computationally expensive. So, I decided to test the Curvature Scale Space (CSS) algorithm with the pre-computed derivatives by separate. After tuning some parameters of the CSS algorithm, I obtained good results when detecting high curvatures values in point cloud segments. Finally, I included the modified code of the CSS feature extractor in the LOAM algorithm.

**Comment by GDUT-Kyle** [comment]
Hello, 
Thank you for your reply. I am a beginner, your paper and code are of great help to me, thank you very much. I still have a question, when the function "computeCurvature" calculates the scale, your code is "sigma = kernelWidth/4000.0". But according to my understanding, I think it should be "sigma = kernelFactor", of course, I don't know if my idea is correct.
